name       : chatty
version    : '0.22'
release    : 26
source     :
    - https://github.com/chatty/chatty/archive/refs/tags/v0.22.tar.gz : 4d5f4236bba0190608e825fa5baf11d718650bf83e6571ab83dd9457af9f888c
license    :
    - GPL-3.0-or-later
    - MIT
component  : network.irc
summary    : Twitch Chat Client
description: |
    Chatty is a Twitch Chat Client for Desktop written in Java featuring many Twitch specific features.
networking : yes
builddeps  :
    - gradle
    - openjdk-17
    - unzip
rundeps    :
    - openjdk-17
environment: |
    JAVA_HOME=/usr/lib64/openjdk-17
    PATH=$JAVA_HOME/bin:$PATH
setup      : |
    %apply_patches
build      : |
    export GRADLE_USER_HOME=$workdir/.gradle
    gradle --no-daemon release
install    : |
    # Unzip to destination
    mkdir -p $installdir/usr/share/chatty
    unzip $workdir/build/releases/Chatty_$version.zip -d $installdir/usr/share/chatty/

    # Remove unneeded files
    rm $installdir/usr/share/chatty/{LICENSE,readme.txt}

    # Install to $PATH
    install -Dm00755 $pkgfiles/chatty.sh  $installdir/usr/bin/chatty

    # Install desktop file
    install -Dm00644 $pkgfiles/chatty.desktop $installdir/usr/share/applications/chatty.desktop

    # Install icons
    for size in 16 64 128; do
    install -Dm00644 src/chatty/gui/app_main_$size.png \
      $installdir/usr/share/icons/hicolor/${size}x${size}/apps/chatty.png
    done

