name       : chatty
version    : 0.8.5.1
release    : 3
source     :
    - https://github.com/chatty/chatty/archive/v0.8.5.1.tar.gz : a1a3de5f821239f010f43e037b0cea66f2f49c3e86d3b638920a916ff80fbf3d
license    : Apache-2.0
component  : network.irc
summary    : Twitch Chat Client
networking : yes
description: |
    Twitch Chat Client written in Java
builddeps  :
    - gradle
    - unzip
rundeps    :
    - openjdk-8
setup      : |
    %patch -p1 < $pkgfiles/disable_version_check.patch
    %patch -p1 < $pkgfiles/user_config_dir.patch
build      : |
    export GRADLE_USER_HOME=/home/build/YPKG/root/chatty/
    gradle --no-daemon release
install    : |
    mkdir -p $installdir/usr/share/chatty
    unzip $workdir/build/releases/Chatty_$version.zip -d $installdir/usr/share/chatty/

    install -Dm755 $pkgfiles/chatty.sh  $installdir/usr/bin/chatty

    install -Dm644 $pkgfiles/chatty.png $installdir/usr/share/pixmaps/chatty.png
    install -Dm755 $pkgfiles/chatty.desktop $installdir/usr/share/applications/chatty.desktop

